version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    groups:
      frontend-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "maven"
    directory: "/tile-compiler"
    schedule:
      interval: "weekly"
    groups:
      compiler-dependencies:
        patterns:
          - "*"
