name: Build Frontend

on:
  workflow_call:
  push:
    paths:
      - 'tile-compiler/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          sparse-checkout: tile-compiler
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
      - name: Build & Deploy
        run: |
          cd tile-compiler
          mvn -B compile deploy
