# This workflow will check commits to contain no images and if dvc is up to date

name: Check Commit
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Check that no images are in the repo
      run: |
        ! find . -name '*.png' | grep .
        ! find . -name '*.jpg' | grep .
        ! find . -name '*.tif' | grep .
        ! find . -name '*.webp' | grep .
    - name: Install dvc
      env:
        GDRIVE_SERVICE_ACCOUNT: ${{ secrets.GDRIVE_SERVICE_ACCOUNT }}
      run: |
        sudo snap install dvc --classic
        echo "$GDRIVE_SERVICE_ACCOUNT" >> /tmp/srvacc.json
        stat --printf="%s" /tmp/srvacc.json
        dvc remote modify imagestore gdrive_use_service_account true
        dvc remote modify imagestore gdrive_service_account_json_file_path /tmp/srvacc.json
    - name: Check if dvc pull works
      run: |
        dvc pull
        dvc checkout
