name: Clean

on:
  workflow_call:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write
  packages: read

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: false
          token: ${{ secrets.ACTIONS_PAT }}
      - name: Compile tiles
        uses: ./.github/compiler-docker
        with:
          entrypoint: '/clean.sh'
      - name: Push changes
        id: push
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Automatic cleaning of geopackages'
          add: 'sources/*'
      