name: Deploy to GitHub Pages

on:
  workflow_call:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Prepare environment
        run: |
          sudo add-apt-repository ppa:ubuntugis/ppa
          sudo apt update && sudo apt install -y libsqlite3-dev zlib1g-dev mmv gdal-bin
          git clone https://github.com/mapbox/tippecanoe.git
          cd tippecanoe
          sudo make -j
          sudo make install
          npm install -g geojson-polygon-labels mapshaper @elastic/spritezero-cli
      - name: Compile
        run: |
          maxzoom=11
          datapath=data-$RANDOM
          cd frontend
          printf "VITE_MAX_ZOOM=$maxzoom\nVITE_DATA_PATH=$datapath" > .env.local
          npm ci
          npm run build
          cd ../tile-compiler
          ./compile.sh $maxzoom shortcut $datapath
      - name: Push to page branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: frontend/dist
