name: Deploy to GitHub Pages

on:
  workflow_call:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          submodules: false
      - name: Compile tiles
        uses: ./.github/compiler-docker
      - name: Push to page branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: frontend/dist