# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Deploy Jekyll with GitHub Pages dependencies preinstalled

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Prepare environment
        run: |
          sudo apt update && sudo apt install -y libsqlite3-dev zlib1g-dev
          git clone https://github.com/mapbox/tippecanoe.git
          cd tippecanoe
          sudo make -j
          sudo make install
          npm install -g geojson-polygon-labels mapshaper @elastic/spritezero-cli
      - name: Compile data
        shell: bash
        run: |
          cd tile-compiler
          ./compile.sh
      - name: Compile frontend
        run: |
          cd frontend
          npm ci
          npm run build
      - name: Push to page branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: frontend/dist
