name: Download entities from wiki

on:
  schedule:
    - cron: "0 */2 * * *"
  workflow_dispatch:

permissions:
  contents: write

# Allow one concurrent deployment
concurrency:
  group: "download"
  cancel-in-progress: true

jobs:
  # Build job
  pull:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Download changes
        run: |
          cd wiki-downloader
          mvn compile
          mvn exec:java -Dexec.mainClass="io.github.pfwikis.DownloadCities"
          mvn exec:java -Dexec.mainClass="io.github.pfwikis.DownloadLoI"
      - name: Push changes
        id: push
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Updating wiki derived json files'
      - name: pull
        if: ${{ steps.push.outputs.pushed }}
        uses: pf-wikis/mapping/.github/workflows/deploy-to-gh-pages.yml@main
