name: Frontend Build

on:
  workflow_call:
  push:
    paths:
      - 'frontend/**'
  workflow_dispatch:

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          sparse-checkout: frontend
      - name: Build Frontend
        run: |
          cd frontend
          npm ci
          npm run build
      
