name: Map Deployment

on:
  workflow_call:
  push:
    branches:
      - main
  workflow_dispatch:
  repository_dispatch:
    types: [data_release] # this is a trigger used by the mapping-data repository

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: false
      - name: Compile tiles
        uses: ./.github/compiler-docker
      - name: Copy map to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: "frontend/dist/*"
          target: /wikis/volumes/map
          strip_components: 2
          overwrite: true
      - name: Delete old files
        uses: garygrossgarten/github-action-ssh@v0.6.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          command: |
            cd /wikis
            find /wikis/volumes/map -mtime +7 -type f -delete
            docker restart page_cache
      # - name: Upload artifact
      #   uses: actions/upload-pages-artifact@v2
      #   with:
      #     path: frontend/dist
      # - name: Deploy to GitHub Pages
      #   id: deployment
      #   uses: actions/deploy-pages@v1
