name: Redirect Deployment

on:
  workflow_call:
  push:
    branches:
      - main
  workflow_dispatch:
  repository_dispatch:
    types: [data_release] # this is a trigger used by the mapping-data repository

permissions:
  contents: write
  pages: write
  id-token: write
  packages: read

# Allow one concurrent deployment
concurrency:
  group: "redirect"
  cancel-in-progress: true

jobs:
  # Build job
  build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: false
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Copy map to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: "frontend/dist/*"
          target: /wikis/volumes/map
          strip_components: 2
          rm: true
      - run: |
          mkdir result
          cp frontend/src/redirect.html result/
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: result
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
